#%RAML 1.0 Library

types:
  Cart: !include schema/request/cart.raml
  DivisionShiftRule: !include schema/request/divisionShiftRule.raml
  Game: !include schema/request/game.raml
  League: !include schema/request/league.raml
  LeagueSpeedrun: !include schema/request/leagueSpeedrun.raml
  PlayoffRule: !include schema/request/playoffRule.raml
  PointRule: !include schema/request/pointRule.raml
  Race: !include schema/request/race.raml
  Runner: !include schema/request/runner.raml
  RaceTime: !include schema/request/raceTime.raml
  RaceTimeUpdate: !include schema/request/raceTimeUpdate.raml
  Speedrun: !include schema/request/speedrun.raml
  System: !include schema/request/system.raml
