#%RAML 1.0 Library

types:
  Cart: !include schema/response/cart.raml
  DivisionShiftRule: !include schema/response/divisionShiftRule.raml
  Game: !include schema/response/game.raml
  League: !include schema/response/league.raml
  LeagueSpeedrun: !include schema/response/leagueSpeedrun.raml
  PlayoffRule: !include schema/response/playoffRule.raml
  PointRule: !include schema/response/pointRule.raml
  Race: !include schema/response/race.raml
  Runner: !include schema/response/runner.raml
  RaceTime: !include schema/response/raceTime.raml
  Speedrun: !include schema/response/speedrun.raml
  System: !include schema/response/system.raml
