type: object
properties:
  gameName:
    type: string
  systemName:
    type: string
    required: true
  isEmulated:
    type: boolean
    required: false
  region:
    type: string
    required: false
  version:
    type: string
    required: false
