type: object
properties:
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  tierLevel:
    type: integer
    required: true
  tierName:
    type: string
    required: true
  promotionRules:
    type: !include qualifierRule.raml
    required: true
  relegationRules:
    type: !include qualifierRule.raml
    required: true
