type: object
properties:
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  runnerName:
    type: string
    required: true
  joinedOn:
    type: string
    required: true
