type: object
properties:
  league:
    type: string
    required: true
  season:
    type: integer
    required: true
  tier:
    type: integer
    required: true
  category:
    type: string
    required: true
  gameName:
    type: string
    required: true
  systemName:
    type: string
    required: true
  isEmulated:
    type: boolean
    required: false
  region:
    type: string
    required: false
  version:
    type: string
    required: false
