type: object
properties:
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  tierLevel:
    type: integer
    required: true
  tierName:
    type: string
    required: true
  pointRules:
    type: !include pointRule.raml
    required: true
