type: object
properties:
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  parentTierLevel:
    type: integer
    required: true
  tierName:
    type: string
    required: true
  startedOn:
    type: datetime
    required: false
  defaultTime:
    type: string
    required: false
  defaultPoints:
    type: boolean
    required: false
  runnerLimit:
    type: integer
    required: false
  registrationEndedOn:
    type: datetime
    required: false
  divisionShifts:
    type: integer
    required: false
  qualifierRules:
    type: string
    required: false
  pointRules:
    type: string
    required: false
  promotionRules:
    type: string
    required: false
  relegationRules:
    type: string
    required: false
