type: object
properties:
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  tierLevel:
    type: integer
    required: true
  raceName:
    type: string
    required: false
  startedOn:
    type: datetime
    required: true
