type: object
properties:
  name:
    type: string
    required: true
  leagueName:
    type: string
    required: true
  season:
    type: integer
    required: true
  tierLevel:
    type: integer
    required: true
  tierName:
    type: string
    required: true
  startedOn:
    type: datetime
    required: true
